name: Build Akarin 1.12.2
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update submodule
        run: git submodule update --init --recursive
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: zulu
      - name: Grant execute permission for script
        run: chmod +x scripts/inst.sh
      - name: Build
        run: ./scripts/inst.sh --setup --remote
      - name: Upload Akarin
        uses: actions/upload-artifact@v3
        with:
          name: Akarin-1.12.2
          path: ./*.jar
