name: Akarin-1.16.5

on: [ push ]

jobs:
  build-11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build
      run: ./akarin jar
    - name: Upload Akarin
      uses: actions/upload-artifact@v2
      with:
        name: akarin-1.16.5
        path: target/build/libs
